name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to TreeScale
        uses: docker/login-action@v1 
        with:
          registry: repo.treescale.com
          username: ${{ secrets.TREESCALE_USERNAME }}
          password: ${{ secrets.TREESCALE_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: zikeji/nwcraft:latest
          build-args: |
            VUE_APP_DISCORD_TAG=${{ secrets.VUE_APP_DISCORD_TAG }}
            VUE_APP_MATAMO_URL=${{ secrets.VUE_APP_MATAMO_URL }}
            VUE_APP_MATAMO_SITEID=${{ secrets.VUE_APP_MATAMO_SITEID }}
            VUE_APP_MATAMO_FILE=${{ secrets.VUE_APP_MATAMO_FILE }}
